Proposal to add `AudioFileSourceFunction` which can generate sound from functions
earlephilhower/ESP8266Audio pull request #383
Opened 2021-04-11 07:40 UTC by hideakitai

Hi @earlephilhower , thank you for this great audio library. I've made some extension named `AudioFileSourceFunction`  that can easily play "raw" audio like sine wave which is generated by functions which has 1 float argument(time) and 1 float return(amplitude). 

```C++
  // AudioFileSourceFunction can generate sound from function
  file = new AudioFileSourceFunction(8.); // [sec]
  file->addAudioGenerators([](const float time) {
    return sin(TWO_PI * 440.f * time);  // C
  });
  // same as other examples
  out = new AudioOutputI2SNoDAC();
  wav = new AudioGeneratorWAV();
  wav->begin(file, out)
```

`AudioFileSourceFunction` generates the WAV file header and its audio data will be generated each time based on the registered function when requested.

```C++
  file = new AudioFileSourceFunction(sec, channels, hz, bit_per_sample);
  // channels   : default = 1
  // hz         : default = 8000 (8000, 11025, 22050, 44100, 48000, etc.)
  // bit/sample : default = 16 (8, 16, 32)
```

The [example for AudioFileSourceFunction](https://github.com/hideakitai/ESP8266Audio/blob/add_source_function/examples/PlayWAVFromFunction/PlayWAVFromFunction.ino) is also added. I'm glad if you see whether this extension can works in your great library.

Thanks
hideakitai

2021-04-11 21:03 UTC, earlephilhower requested changes
Very ingenious use of lambdas!  Add the appropriate headers and I'd be happy to merge.

This looks like it would also be useful to make things like DTMF tones as some people have requested.

2021-04-11 21:03 UTC, earlephilhower commented on src/AudioFileSourceFunction.cpp
> +#include "AudioFileSourceFunction.h"
Can you please add the GPL header with your name and (c)?

2021-04-11 21:03 UTC, earlephilhower commented on src/AudioFileSourceFunction.h
> +#ifndef _AUDIOFILESOURCEFUNCTION_H
GPL header, please

2021-04-12 00:32 UTC, hideakitai commented
Thanks for reviewing. I've added the GPL headers and also some supplements to example for someone who is not familiar to lambdas.

- Use lambda capture by default
- Add usage of pre-defined function instead of lambda

If you have any feedback, please let me know. Thank you!

2021-04-12 01:37 UTC, earlephilhower approved these changes

2021-04-12 01:37 UTC, merged