Allow compilation in recent ARDUINO ESP32 RELEASES 2.0.1 and 2.0.2…
earlephilhower/ESP8266Audio pull request #502
Opened 2022-03-09 21:50 UTC by Martin-Laclaustra

… by excluding AudioGeneratorMIDI
This is a temporary solution that drops MIDI support to make this library available in most recent ESP32-Arduino cores, which have a compiler bug that renders this code incompatible.

(Temporary) Fix for:
https://github.com/earlephilhower/ESP8266Audio/issues/498
https://github.com/earlephilhower/ESP8266Audio/issues/464
https://github.com/earlephilhower/ESP8266Audio/issues/440

2022-03-09 21:57 UTC, Martin-Laclaustra commented
I see that "core_version.h" is not available in all contexts (I verified it was in ESP32 and ESP8266). May be this proposal serves as inspiration for some to find a general solution. (Mine works fine locally in my computer)

2022-03-10 05:18 UTC, Martin-Laclaustra commented
I fixed the error arising from "core_version.h" not being available in all contexts.
Currently some tests fail, but the errors seem unrelated to this pull request.
I hope that this can be merged and this library be made available again for ESP32 in the most recent core releases.

2022-03-10 10:54 UTC, earlephilhower requested changes
The issue is the GCC version, so why not just use
````
#if __GNUC__ == 8
// Do not build, GCC8 has a compiler bug
#else
....
````

That way if V2.0.3 comes out w/the same compiler it's still good.

2022-03-10 10:59 UTC, earlephilhower commented
Oh, and thanks for the PR!

2022-03-10 17:04 UTC, Martin-Laclaustra commented
Done!

2022-03-10 17:13 UTC, earlephilhower approved these changes
Thanks!

2022-03-10 17:14 UTC, merged

2022-08-31 14:55 UTC, earlephilhower commented
@shuai132, I am not seeing GNUC as 8 in 10.3.  Here is my output from the ESP8266 core:
````
echo | ~/Arduino/hardware/esp8266com/esp8266/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc -dM -E - | grep GNU
#define __GNUC_PATCHLEVEL__ 0
#define __GNUC__ 10
#define __GNUC_STDC_INLINE__ 1
#define __GNUC_MINOR__ 3
````

I would be fine adding additional conditions to the `#if`.  Can you run the same command line with your working GCC 8.4 so we can see what defines come out?  Maybe we can change it to 
````
#if (__GNUC__ == 8) && (__GNUC_MINOR__ < 4)
// GCC bug prevents compilation
#else
...
````

2022-08-31 15:19 UTC, shuai132 commented
Sorry, 10.3 is correct, it's my IDE(clion) issue(host compiler's notice).
I'm using platformio:
toolchain path: `~/.platformio/packages/toolchain-xtensa/bin`
```
➜  bin echo | ./xtensa-lx106-elf-gcc -dM -E - | grep GNU
#define __GNUC_PATCHLEVEL__ 0
#define __GNUC__ 10
#define __GNUC_STDC_INLINE__ 1
#define __GNUC_MINOR__ 3
```

BTW:
we do need like this: 
```
#if (__GNUC__ == 8) && (__GNUC_MINOR__ < 4)
```
I have tested it, it works on my esp32 compiler.

2022-08-31 15:20 UTC, earlephilhower commented
@shuai132 great.  Would you like to make the PR adding the `&& (__GNUC_MINOR__ < 4)` to the condition?

2022-08-31 17:15 UTC, shuai132 commented
Thanks，my pleasure,
PR: https://github.com/earlephilhower/ESP8266Audio/pull/567