Add support for I2S MCLK.
earlephilhower/ESP8266Audio pull request #594
Opened 2022-12-24 15:20 UTC by DatanoiseTV

This commit implements support for generating basic 256*fs MCLK using the APLL.

2022-12-26 16:54 UTC, earlephilhower requested changes

2022-12-26 16:54 UTC, earlephilhower commented on src/AudioOutputI2S.cpp
> +bool AudioOutputI2S::SetPinout(int bclk, int wclk, int dout, int mclk)
Can you please add `(void) mclk` in the non-ESP32 path?  OTW we get fatal warning/errors.

2022-12-26 16:54 UTC, earlephilhower commented on src/AudioOutputI2S.cpp
> +bool AudioOutputI2S::SetMclk(bool enabled){
Same as other comment, for `enabled`.

2022-12-26 17:32 UTC, DatanoiseTV commented on src/AudioOutputI2S.cpp
> +bool AudioOutputI2S::SetMclk(bool enabled){
Done.

2022-12-26 20:18 UTC, earlephilhower commented
Something got weird on the commit/pushes and your `(void)` marker seems to have been lost (see the 8266 failures).  Can you take a look again, please?

2022-12-26 20:24 UTC, DatanoiseTV commented
> Something got weird on the commit/pushes and your `(void)` marker seems to have been lost (see the 8266 failures). Can you take a look again, please?

I think now it is right.

2022-12-30 22:34 UTC, earlephilhower commented
OK, we're almost there.  The change in the 8266 needs to applied to the RP2040 branch and we should all be OK.  The joys of supporting 3 different (actually w/the ESP32-XXs maybe 6?) boards.

2023-01-04 01:10 UTC, earlephilhower commented
@DatanoiseTV can you pull in the latest `master`?    The ESP8266 internal test scripts changed over in that repo, so I needed to hack the tests here that used it.  It should now work and we should be able to hopefully get a complete run.

2023-01-04 17:45 UTC, earlephilhower approved these changes

2023-01-04 17:46 UTC, merged

2023-03-11 07:54 UTC, FREEWING-JP commented
I tested CS4344 I2S DAC with ESP32-D0WD-V3 (revision v3.0) .
* CS4344 need MCLK
It works Fine !
Thank you !